spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/course_schema
    username: root
    password: 300105
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: user
logging:
  level:
    root: warn
