spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/course_schema
    username: root
    password: 300105
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: user
logging:
  level:
    root: warn
jwt:
  sign-key: nk8Qd16puruJS4NQcIrCl3w/Z4y9m1qL2+im6FKk+/6omRgXe74MChieETz8AyaGhiANe1nT6x17aOxyz3Gnow==
  access-duration: 3000000