spring:
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: off
  datasource:
    url: ${MYSQL_CONNECTION}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: user
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
logging:
  level:
    root: warn
jwt:
  sign-key: nk8Qd16puruJS4NQcIrCl3w/Z4y9m1qL2+im6FKk+/6omRgXe74MChieETz8AyaGhiANe1nT6x17aOxyz3Gnow==
  access-duration: 300000
  refresh-duration: 50000000